### ISSUE TITLE
Service worker registration failed. Status code: 3 (latest version of vite)

### ISSUE THREAD

**Issue by ionutanin** [sinanbekar/browser-extension-react-typescript-starter#56]
Having some issues on dev with service worker not working. Any solution for this please?

<img width="619" alt="image" src="https://github.com/sinanbekar/browser-extension-react-typescript-starter/assets/2699091/3b53b31d-2060-40f6-8cae-2437bbe7a694">

**Comment by sinanbekar** [comment]
Thanks for reaching out. For this time you should not update core package versions (like vite and @crxjs/vite-plugin). As mentioned in the ``README.md`` [@crxjs/vite-plugin](https://github.com/crxjs/chrome-extension-tools) powers the development side of this starter. This plugin is a bit complex and updating vite can be breaking. If you have a strong reason to update, you should follow the plugin releases to match and maybe manually test it.
